(function() {var implementors = {};
implementors["actix_web"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"https://docs.rs/bytes/0.4.9/bytes/bytes/struct.Bytes.html\" title=\"struct bytes::bytes::Bytes\">Bytes</a>&gt; for <a class=\"enum\" href=\"actix_web/enum.Binary.html\" title=\"enum actix_web::Binary\">Binary</a>",synthetic:false,types:["actix_web::body::Binary"]},{text:"impl&lt;H:&nbsp;<a class=\"trait\" href=\"actix_web/server/trait.IntoHttpHandler.html\" title=\"trait actix_web::server::IntoHttpHandler\">IntoHttpHandler</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.tuple.html\">(</a><a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/alloc/boxed/struct.Box.html\" title=\"struct alloc::boxed::Box\">Box</a>&lt;Service&gt;, <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/alloc/vec/struct.Vec.html\" title=\"struct alloc::vec::Vec\">Vec</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.tuple.html\">(</a>Token, <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/net/tcp/struct.TcpListener.html\" title=\"struct std::net::tcp::TcpListener\">TcpListener</a><a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.tuple.html\">)</a>&gt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.tuple.html\">)</a>&gt; for <a class=\"struct\" href=\"actix_web/server/struct.HttpServer.html\" title=\"struct actix_web::server::HttpServer\">HttpServer</a>&lt;H&gt;",synthetic:false,types:["actix_web::server::http::HttpServer"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u8.html\">u8</a>&gt; for <a class=\"enum\" href=\"actix_web/ws/enum.OpCode.html\" title=\"enum actix_web::ws::OpCode\">OpCode</a>",synthetic:false,types:["actix_web::ws::proto::OpCode"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u16.html\">u16</a>&gt; for <a class=\"enum\" href=\"actix_web/ws/enum.CloseCode.html\" title=\"enum actix_web::ws::CloseCode\">CloseCode</a>",synthetic:false,types:["actix_web::ws::proto::CloseCode"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
